version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dev_pass
      MYSQL_DATABASE: graphql_todo
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_pass
    ports:
      - "9906:3306"